Remove macos-14 for now due to API rate limit error
Error: API rate limit exceeded for 13.105.117.173. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)